### ISSUE TITLE
Updated My Blogs page

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/skyblog#33]
**Is your feature request related to a problem? Please describe.**
Update layout for my blogs page, especially when there are no blogs.

**Describe the solution you'd like**
The blank avatar icon is weird :-) 

I'm not sure if that is a place holder of if that is the profile DAC avatar that is loading low. If it is the profile DAC avatar we should more it above the break with the other profile information. 

If it is a placeholder we should remove it and replace it with something like `make your first blog`

**Describe alternatives you've considered**

**Additional context**
<img width="437" alt="Screen Shot 2021-08-28 at 4 59 14 PM" src="https://user-images.githubusercontent.com/15232757/131230904-e27bb566-659c-4367-9419-f86a71899ead.png">

**Comment by kevin-carlson** [comment]
The blank avatar is supposed to be shown when the profile dac avatar is not set. 
There is a bug with the userProfile DAC that doesn't allow a user to update their profile, so if you have a picture set and it is not showing up, then it is probably because I incorrectly inferred the data structure of the user's avatar.

**Comment by MSevey** [comment]
> The blank avatar is supposed to be shown when the profile dac avatar is not set.
> There is a bug with the userProfile DAC that doesn't allow a user to update their profile, so if you have a picture set and it is not showing up, then it is probably because I incorrectly inferred the data structure of the user's avatar.

Ok, let's move it above that divider line then so it is with the rest of the profile information.  Positioned to the left of the current info.
